name: PrisonEssentials
author: DaRealAqua
version: 2.0.0
main: Prison\Main
api: 3.0.0
depend: [PurePerms, MineReset, EconomyAPI, FormAPI]
description: "A prison plugin-core for beginners"
permissions:
  prison.setrank:
    description: "Allows to use /setrank command"
    default: op
  prison.setprestige:
    description: "Allows to use /setprestige command"
    default: op
